// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.1
// source: food-delivery-protos/product.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductRatingUReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId string  `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Rate      float32 `protobuf:"fixed32,2,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *ProductRatingUReq) Reset() {
	*x = ProductRatingUReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_delivery_protos_product_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductRatingUReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRatingUReq) ProtoMessage() {}

func (x *ProductRatingUReq) ProtoReflect() protoreflect.Message {
	mi := &file_food_delivery_protos_product_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRatingUReq.ProtoReflect.Descriptor instead.
func (*ProductRatingUReq) Descriptor() ([]byte, []int) {
	return file_food_delivery_protos_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductRatingUReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductRatingUReq) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type ProductCountUReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId string  `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count     float32 `protobuf:"fixed32,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ProductCountUReq) Reset() {
	*x = ProductCountUReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_delivery_protos_product_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductCountUReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCountUReq) ProtoMessage() {}

func (x *ProductCountUReq) ProtoReflect() protoreflect.Message {
	mi := &file_food_delivery_protos_product_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCountUReq.ProtoReflect.Descriptor instead.
func (*ProductCountUReq) Descriptor() ([]byte, []int) {
	return file_food_delivery_protos_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductCountUReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductCountUReq) GetCount() float32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_food_delivery_protos_product_proto protoreflect.FileDescriptor

var file_food_delivery_protos_product_proto_rawDesc = []byte{
	0x0a, 0x22, 0x66, 0x6f, 0x6f, 0x64, 0x2d, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x1a, 0x1f,
	0x66, 0x6f, 0x6f, 0x64, 0x2d, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x46, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x55, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x47, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x32, 0x88, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x12, 0x1b, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x55, 0x52, 0x65, 0x71,
	0x1a, 0x0e, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x56, 0x6f, 0x69, 0x64,
	0x12, 0x39, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1a, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x64, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x0c, 0x5a, 0x0a, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_food_delivery_protos_product_proto_rawDescOnce sync.Once
	file_food_delivery_protos_product_proto_rawDescData = file_food_delivery_protos_product_proto_rawDesc
)

func file_food_delivery_protos_product_proto_rawDescGZIP() []byte {
	file_food_delivery_protos_product_proto_rawDescOnce.Do(func() {
		file_food_delivery_protos_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_food_delivery_protos_product_proto_rawDescData)
	})
	return file_food_delivery_protos_product_proto_rawDescData
}

var file_food_delivery_protos_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_food_delivery_protos_product_proto_goTypes = []any{
	(*ProductRatingUReq)(nil), // 0: delivery.ProductRatingUReq
	(*ProductCountUReq)(nil),  // 1: delivery.ProductCountUReq
	(*Void)(nil),              // 2: delivery.Void
}
var file_food_delivery_protos_product_proto_depIdxs = []int32{
	0, // 0: delivery.ProductService.UpdateRating:input_type -> delivery.ProductRatingUReq
	1, // 1: delivery.ProductService.UpdateCount:input_type -> delivery.ProductCountUReq
	2, // 2: delivery.ProductService.UpdateRating:output_type -> delivery.Void
	2, // 3: delivery.ProductService.UpdateCount:output_type -> delivery.Void
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_food_delivery_protos_product_proto_init() }
func file_food_delivery_protos_product_proto_init() {
	if File_food_delivery_protos_product_proto != nil {
		return
	}
	file_food_delivery_protos_void_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_food_delivery_protos_product_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ProductRatingUReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_delivery_protos_product_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ProductCountUReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_food_delivery_protos_product_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_food_delivery_protos_product_proto_goTypes,
		DependencyIndexes: file_food_delivery_protos_product_proto_depIdxs,
		MessageInfos:      file_food_delivery_protos_product_proto_msgTypes,
	}.Build()
	File_food_delivery_protos_product_proto = out.File
	file_food_delivery_protos_product_proto_rawDesc = nil
	file_food_delivery_protos_product_proto_goTypes = nil
	file_food_delivery_protos_product_proto_depIdxs = nil
}
